### ISSUE TITLE
Close colourinput on choice select

### ISSUE THREAD

**Issue by ghost** [daattali/jquery-colourpicker#5]
Pull requests somehow forward me to claviska/jquery, so i'll post it as issue. 

ColourInput would benefit from functionality that closes it when a user has made a choice (clicked a color) as it would save the user the hassle of having to click outside of the dropdown to get rid of it.  It would make it substantially more user friendly if this is a feature / optional

Mark

**Comment by daattali** [comment]
Did you have a pull request to make? I would happily welcome that

**Comment by ghost** [comment]
the github won't allow me, it redirects me to to the parent github as I
mentioned


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by daattali** [comment]
That's strange, others have successfully done PRs in this repo. What workflow are you trying to do to submit a PR?

**Comment by ghost** [comment]
I don't currently have a workflow on github. I'm working purely off line on
my project at this point. perhaps that's why

**Comment by daattali** [comment]
Sure, what's your workflow off github then? I'm trying to understand at what step do you get stuck, because it is possible to do a PR to this repo.

**Comment by ghost** [comment]
Hi Dean,

sorry for the bother. Ok, I'm trying to learn what i'm doing wrong, and
staying patient here. I just screen recorded what happens when I try to
make a PR, and once again it ends up on the master page, not your github of
colourInput. Notice the red warnings about pull requests I get to see.

Mark

here is a link to the recording

https://gph.is/g/ZPxBpBZ

**Comment by daattali** [comment]
Ah I see. That's the way to make pull requests if you already have a branch with the code you want to merge. Did you already implement the solution in a branch in your own repository?

If not, the first step is to clone this repository so that you have your own copy, make the necessary changes to fix the issue, and then make a pull request using your changes.

**Comment by ghost** [comment]
Dean,

like I said, I don't use github at this moment, and I did not want to
forward any fixes. I merely wanted to make a suggestion for improvement
(described in English) to make colourinput better. It was you who read that
in my first email and said, please make a PR........ We could have gotten
the suggestion across dozens of times by now without the whole discussion
about PRs and github haha. Sorry, just seems a bit funny to me.

cheers, Mark

**Comment by daattali** [comment]
Ah I see your confusion. If you read my initial message, I said you should open this request in this repo rather than the other repo. I literally meant you should open an issue with this feature request in the correct repository. When you talked about "pull requests" I took that to understand that you actually have a code fix because that's what a pull request is!

**Comment by ghost** [comment]
Ah I see. ok glad we got it figured out now, and I learned a little bit
more about git in the process.
Thanks Dean!

**Comment by ghost** [comment]
after all this hassle to post it, any clue if and when you might get around to this suggestion Dean?

**Comment by daattali** [comment]
I don't know when or if I would find time to dedicate to this. Maybe if enough other people want to see this feature. If anyone who knows jacascript wants to try to figure this out I would be happy to review

**Comment by daattali** [comment]
Is your usecase specifically for the case when there is a specific set of available colour choices, or when the entire spectrum of colours is available?

**Comment by ghost** [comment]
Im using a custom set of 40 colors in my shiny app

**Comment by ghost** [comment]
I see you added something, do I need to add an argument to the colourinput
to activate it? And thanks for the added feature!

**Comment by ghost** [comment]
I downloaded the developpers version and added closeOnClick = T, but it returns unused argument. 
  colour_input <- colourInput(inputId = Idname, label = NULL,
                                         palette = "limited", allowedCols = TheColors,
                                         value = colorX[x], closeOnClick = T,
                                         showColour = "background", returnName = FALSE)

**Comment by ghost** [comment]
OK, full removal and re installation of the package devtools solved the issue. Not sure what went wrong. Thanks Dean for adding it!
